-- 20260910150000_breeds_seed.sql
-- Наполнение справочника пород (ADR-014).
--
-- Список курированный, а не полный: FCI признаёт около 360 пород собак, и
-- переносить их сюда по памяти — верный способ насажать ошибок в данные, по
-- которым потом будут сравнивать симптомы и корма. Здесь распространённые в
-- России породы плюс дизайнерские метисы, которых в FCI нет вовсе. Пробелы
-- закрывает pets.breed_custom, справочник расширяется отдельной миграцией.
--
-- sort_order: 0 — метис, 10 — самые частые, 50 — непризнанные, 100 — прочие.
-- fci_group проставлена только там, где она достоверна.

insert into public.breeds
  (species, name_ru, name_en, recognized, fci_group, aliases, sort_order)
values
  ('dog', 'Метис / беспородная', 'Mixed breed', false, null, array['дворняга', 'беспородный', 'метис'], 0),
  ('cat', 'Метис / беспородная', 'Mixed breed', false, null, array['дворняга', 'беспородный', 'метис'], 0),
  ('dog', 'Немецкая овчарка', 'German Shepherd Dog', true, 1, array['овчарка', 'нко'], 10),
  ('dog', 'Лабрадор-ретривер', 'Labrador Retriever', true, 8, array['лабрадор'], 10),
  ('dog', 'Золотистый ретривер', 'Golden Retriever', true, 8, array['голден ретривер', 'голден'], 10),
  ('dog', 'Чихуахуа', 'Chihuahua', true, 9, '{}', 10),
  ('dog', 'Йоркширский терьер', 'Yorkshire Terrier', true, 3, array['йорк'], 10),
  ('dog', 'Померанский шпиц', 'Pomeranian', true, 5, array['померанец', 'шпиц'], 10),
  ('dog', 'Такса', 'Dachshund', true, 4, '{}', 10),
  ('dog', 'Джек-рассел-терьер', 'Jack Russell Terrier', true, 3, array['джек рассел'], 10),
  ('dog', 'Французский бульдог', 'French Bulldog', true, 9, array['француз'], 10),
  ('dog', 'Сибирский хаски', 'Siberian Husky', true, 5, array['хаски'], 10),
  ('dog', 'Вельш-корги пемброк', 'Welsh Corgi Pembroke', true, 1, array['корги'], 10),
  ('dog', 'Бигль', 'Beagle', true, 6, '{}', 10),
  ('dog', 'Мальтезе', 'Maltese', true, 9, array['мальтийская болонка', 'мальтеза'], 10),
  ('dog', 'Ши-тцу', 'Shih Tzu', true, 9, array['шитцу'], 10),
  ('dog', 'Среднеазиатская овчарка', 'Central Asian Shepherd Dog', true, 2, array['алабай', 'среднеазиат'], 10),
  ('dog', 'Русский той', 'Russian Toy', true, 9, array['той-терьер', 'русский той-терьер'], 10),
  ('dog', 'Мопс', 'Pug', true, 9, '{}', 10),
  ('dog', 'Пудель', 'Poodle', true, 9, '{}', 10),
  ('dog', 'Мальтипу', 'Maltipoo', false, null, array['мальти-пу'], 50),
  ('dog', 'Кокапу', 'Cockapoo', false, null, '{}', 50),
  ('dog', 'Голдендудль', 'Goldendoodle', false, null, '{}', 50),
  ('dog', 'Лабрадудль', 'Labradoodle', false, null, '{}', 50),
  ('dog', 'Кавапу', 'Cavapoo', false, null, '{}', 50),
  ('dog', 'Помски', 'Pomsky', false, null, '{}', 50),
  ('dog', 'Шипу', 'Shihpoo', false, null, '{}', 50),
  ('dog', 'Йоркипу', 'Yorkipoo', false, null, '{}', 50),
  ('dog', 'Бернедудль', 'Bernedoodle', false, null, '{}', 50),
  ('dog', 'Аусидудль', 'Aussiedoodle', false, null, '{}', 50),
  ('dog', 'Шнудль', 'Schnoodle', false, null, '{}', 50),
  ('dog', 'Пагл', 'Puggle', false, null, '{}', 50),
  ('dog', 'Чорки', 'Chorkie', false, null, '{}', 50),
  ('dog', 'Американский питбультерьер', 'American Pit Bull Terrier', false, null, array['питбуль', 'питбультерьер'], 50),
  ('dog', 'Бивер-йоркширский терьер', 'Biewer Terrier', false, null, array['бивер'], 50),
  ('dog', 'Английский бульдог', 'English Bulldog', true, 2, '{}', 100),
  ('dog', 'Аляскинский маламут', 'Alaskan Malamute', true, 5, array['маламут'], 100),
  ('dog', 'Вельш-корги кардиган', 'Welsh Corgi Cardigan', true, 1, '{}', 100),
  ('dog', 'Той-пудель', 'Toy Poodle', true, 9, '{}', 100),
  ('dog', 'Английский кокер-спаниель', 'English Cocker Spaniel', true, 8, array['кокер'], 100),
  ('dog', 'Американский кокер-спаниель', 'American Cocker Spaniel', true, 8, '{}', 100),
  ('dog', 'Русский спаниель', 'Russian Spaniel', true, null, '{}', 100),
  ('dog', 'Кавказская овчарка', 'Caucasian Shepherd Dog', true, 2, array['кавказец'], 100),
  ('dog', 'Восточноевропейская овчарка', 'East European Shepherd', true, null, array['вео'], 100),
  ('dog', 'Бельгийская овчарка малинуа', 'Belgian Shepherd Malinois', true, 1, array['малинуа'], 100),
  ('dog', 'Ротвейлер', 'Rottweiler', true, 2, '{}', 100),
  ('dog', 'Доберман', 'Dobermann', true, 2, '{}', 100),
  ('dog', 'Боксёр', 'Boxer', true, 2, array['немецкий боксёр'], 100),
  ('dog', 'Стаффордширский бультерьер', 'Staffordshire Bull Terrier', true, 3, array['стаффи'], 100),
  ('dog', 'Американский стаффордширский терьер', 'American Staffordshire Terrier', true, 3, array['амстафф'], 100),
  ('dog', 'Бультерьер', 'Bull Terrier', true, 3, '{}', 100),
  ('dog', 'Кане-корсо', 'Cane Corso', true, 2, '{}', 100),
  ('dog', 'Бордоский дог', 'Dogue de Bordeaux', true, 2, '{}', 100),
  ('dog', 'Немецкий дог', 'Great Dane', true, 2, array['дог'], 100),
  ('dog', 'Английский мастиф', 'English Mastiff', true, 2, array['мастиф'], 100),
  ('dog', 'Тибетский мастиф', 'Tibetan Mastiff', true, 2, '{}', 100),
  ('dog', 'Бернский зенненхунд', 'Bernese Mountain Dog', true, 2, array['бернер'], 100),
  ('dog', 'Сенбернар', 'St. Bernard', true, 2, '{}', 100),
  ('dog', 'Ньюфаундленд', 'Newfoundland', true, 2, '{}', 100),
  ('dog', 'Леонбергер', 'Leonberger', true, 2, '{}', 100),
  ('dog', 'Пиренейская горная собака', 'Pyrenean Mountain Dog', true, 2, '{}', 100),
  ('dog', 'Аргентинский дог', 'Dogo Argentino', true, 2, '{}', 100),
  ('dog', 'Шарпей', 'Shar Pei', true, 2, '{}', 100),
  ('dog', 'Чау-чау', 'Chow Chow', true, 5, '{}', 100),
  ('dog', 'Акита-ину', 'Akita', true, 5, array['акита'], 100),
  ('dog', 'Сиба-ину', 'Shiba Inu', true, 5, array['шиба-ину'], 100),
  ('dog', 'Самоед', 'Samoyed', true, 5, array['самоедская лайка'], 100),
  ('dog', 'Западносибирская лайка', 'West Siberian Laika', true, 5, array['лайка'], 100),
  ('dog', 'Басенджи', 'Basenji', true, 5, '{}', 100),
  ('dog', 'Шелти', 'Shetland Sheepdog', true, 1, array['шетландская овчарка'], 100),
  ('dog', 'Длинношёрстный колли', 'Rough Collie', true, 1, array['колли'], 100),
  ('dog', 'Бордер-колли', 'Border Collie', true, 1, '{}', 100),
  ('dog', 'Австралийская овчарка', 'Australian Shepherd', true, 1, array['аусси'], 100),
  ('dog', 'Бобтейл', 'Old English Sheepdog', true, 1, array['староанглийская овчарка'], 100),
  ('dog', 'Пекинес', 'Pekingese', true, 9, '{}', 100),
  ('dog', 'Папильон', 'Papillon', true, 9, array['континентальный той-спаниель'], 100),
  ('dog', 'Кавалер-кинг-чарльз-спаниель', 'Cavalier King Charles Spaniel', true, 9, array['кавалер'], 100),
  ('dog', 'Бишон фризе', 'Bichon Frise', true, 9, array['бишон'], 100),
  ('dog', 'Котон-де-тулеар', 'Coton de Tulear', true, 9, '{}', 100),
  ('dog', 'Японский хин', 'Japanese Chin', true, 9, '{}', 100),
  ('dog', 'Лхаса апсо', 'Lhasa Apso', true, 9, '{}', 100),
  ('dog', 'Китайская хохлатая', 'Chinese Crested Dog', true, 9, '{}', 100),
  ('dog', 'Цвергшнауцер', 'Miniature Schnauzer', true, 2, array['миниатюрный шнауцер'], 100),
  ('dog', 'Миттельшнауцер', 'Standard Schnauzer', true, 2, '{}', 100),
  ('dog', 'Ризеншнауцер', 'Giant Schnauzer', true, 2, '{}', 100),
  ('dog', 'Русский чёрный терьер', 'Black Russian Terrier', true, 2, array['чёрный терьер'], 100),
  ('dog', 'Вест-хайленд-уайт-терьер', 'West Highland White Terrier', true, 3, array['вестик'], 100),
  ('dog', 'Скотч-терьер', 'Scottish Terrier', true, 3, array['шотландский терьер'], 100),
  ('dog', 'Фокстерьер', 'Fox Terrier', true, 3, '{}', 100),
  ('dog', 'Эрдельтерьер', 'Airedale Terrier', true, 3, '{}', 100),
  ('dog', 'Ягдтерьер', 'German Hunting Terrier', true, 3, array['немецкий ягдтерьер'], 100),
  ('dog', 'Веймаранер', 'Weimaraner', true, 7, '{}', 100),
  ('dog', 'Курцхаар', 'German Shorthaired Pointer', true, 7, array['немецкая короткошёрстная легавая'], 100),
  ('dog', 'Дратхаар', 'German Wirehaired Pointer', true, 7, '{}', 100),
  ('dog', 'Ирландский сеттер', 'Irish Setter', true, 7, '{}', 100),
  ('dog', 'Английский сеттер', 'English Setter', true, 7, '{}', 100),
  ('dog', 'Пойнтер', 'Pointer', true, 7, '{}', 100),
  ('dog', 'Русская псовая борзая', 'Borzoi', true, 10, array['борзая'], 100),
  ('dog', 'Уиппет', 'Whippet', true, 10, '{}', 100),
  ('dog', 'Грейхаунд', 'Greyhound', true, 10, '{}', 100),
  ('dog', 'Афганская борзая', 'Afghan Hound', true, 10, '{}', 100),
  ('dog', 'Салюки', 'Saluki', true, 10, '{}', 100),
  ('dog', 'Ирландский волкодав', 'Irish Wolfhound', true, 10, '{}', 100),
  ('dog', 'Русская гончая', 'Russian Hound', true, 6, array['гончая'], 100),
  ('dog', 'Бассет-хаунд', 'Basset Hound', true, 6, array['бассет'], 100),
  ('dog', 'Далматин', 'Dalmatian', true, 6, array['далматинец'], 100),
  ('dog', 'Родезийский риджбек', 'Rhodesian Ridgeback', true, 6, array['риджбек'], 100),
  ('dog', 'Бладхаунд', 'Bloodhound', true, 6, '{}', 100),
  ('cat', 'Мейн-кун', 'Maine Coon', true, null, array['кун'], 10),
  ('cat', 'Британская короткошёрстная', 'British Shorthair', true, null, array['британец', 'британка'], 10),
  ('cat', 'Шотландская вислоухая', 'Scottish Fold', true, null, array['скоттиш-фолд', 'вислоухая'], 10),
  ('cat', 'Шотландская прямоухая', 'Scottish Straight', true, null, array['скоттиш-страйт'], 10),
  ('cat', 'Сибирская', 'Siberian', true, null, '{}', 10),
  ('cat', 'Сфинкс', 'Canadian Sphynx', true, null, array['канадский сфинкс'], 10),
  ('cat', 'Бенгальская', 'Bengal', true, null, array['бенгал'], 10),
  ('cat', 'Рэгдолл', 'Ragdoll', true, null, '{}', 10),
  ('cat', 'Персидская', 'Persian', true, null, '{}', 10),
  ('cat', 'Русская голубая', 'Russian Blue', true, null, '{}', 10),
  ('cat', 'Манчкин', 'Munchkin', false, null, '{}', 50),
  ('cat', 'Пиксибоб', 'Pixie-bob', false, null, '{}', 50),
  ('cat', 'Ликой', 'Lykoi', false, null, '{}', 50),
  ('cat', 'Донской сфинкс', 'Donskoy', true, null, '{}', 100),
  ('cat', 'Петерболд', 'Peterbald', true, null, '{}', 100),
  ('cat', 'Сиамская', 'Siamese', true, null, '{}', 100),
  ('cat', 'Тайская', 'Thai', true, null, '{}', 100),
  ('cat', 'Ориентальная', 'Oriental Shorthair', true, null, '{}', 100),
  ('cat', 'Абиссинская', 'Abyssinian', true, null, '{}', 100),
  ('cat', 'Сомали', 'Somali', true, null, '{}', 100),
  ('cat', 'Норвежская лесная', 'Norwegian Forest Cat', true, null, '{}', 100),
  ('cat', 'Невская маскарадная', 'Neva Masquerade', true, null, '{}', 100),
  ('cat', 'Бурманская', 'Burmese', true, null, '{}', 100),
  ('cat', 'Бомбейская', 'Bombay', true, null, '{}', 100),
  ('cat', 'Бурмилла', 'Burmilla', true, null, '{}', 100),
  ('cat', 'Египетская мау', 'Egyptian Mau', true, null, '{}', 100),
  ('cat', 'Саванна', 'Savannah', true, null, '{}', 100),
  ('cat', 'Оцикет', 'Ocicat', true, null, '{}', 100),
  ('cat', 'Мэнкс', 'Manx', true, null, '{}', 100),
  ('cat', 'Курильский бобтейл', 'Kurilian Bobtail', true, null, '{}', 100),
  ('cat', 'Американский керл', 'American Curl', true, null, '{}', 100),
  ('cat', 'Американская короткошёрстная', 'American Shorthair', true, null, '{}', 100),
  ('cat', 'Девон-рекс', 'Devon Rex', true, null, '{}', 100),
  ('cat', 'Корниш-рекс', 'Cornish Rex', true, null, '{}', 100),
  ('cat', 'Селкирк-рекс', 'Selkirk Rex', true, null, '{}', 100),
  ('cat', 'Турецкая ангора', 'Turkish Angora', true, null, array['ангора'], 100),
  ('cat', 'Турецкий ван', 'Turkish Van', true, null, '{}', 100),
  ('cat', 'Экзотическая короткошёрстная', 'Exotic Shorthair', true, null, array['экзот'], 100),
  ('cat', 'Шартрез', 'Chartreux', true, null, '{}', 100),
  ('cat', 'Балинезийская', 'Balinese', true, null, '{}', 100),
  ('cat', 'Рагамаффин', 'Ragamuffin', true, null, '{}', 100)
on conflict (species, name_ru) do nothing;

-- DOWN:
-- delete from public.breeds;
